accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:pk>/', views.detail, name='detail'),
    path('update/', views.update, name='update'),
    path('password/', views.password_update, name='password_update'),
    path('delete/', views.delete, name='delete'),
    path('<int:pk>/follow/', views.follow, name='follow'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("reviews/", include("reviews.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("search/", views.search, name="search"),
    path("<int:pk>/comments/", views.comments_create, name="comments_create"),
    path(
        "<int:review_pk>/comments/<int:comment_pk>/delete/",
        views.comments_delete,
        name="comments_delete",
    ),
    path("<int:review_pk>/likes/", views.likes, name="likes"),
]

reviews/models.py
from django.db import models

from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

from django.conf import settings


# Create your models here.
class Review(models.Model):
    star_grade = (
        ("1", "🤩"),
        ("2", "🤩🤩"),
        ("3", "🤩🤩🤩"),
        ("4", "🤩🤩🤩🤩"),
        ("5", "🤩🤩🤩🤩🤩"),
    )

    title = models.CharField(max_length=100)
    content = models.TextField()
    movie_name = models.CharField(max_length=100)
    grade = models.CharField(max_length=1, choices=star_grade)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(400, 300)],
        format="JPEG",
        options={"quality": 80},
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_reviews"
    )


class Comment(models.Model):
    content = models.TextField(max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

reviews/forms.py
from dataclasses import fields
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = "__all__"
        exclude = ("user", "like_users")
        labels = {
            'title': '글 제목',
            'content': '글 내용',
            'movie_name': '영화 제목',
            'grade': '평점',
            'image': '이미지 파일'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)
        labels = {
            'content': '댓글',
        }

reviews/views.py
from django.shortcuts import render, redirect

from .forms import ReviewForm, CommentForm
from reviews.models import Review, Comment

from django.db.models import Q

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

# Create your views here.


def index(request):
    reviews = Review.objects.all()
    context = {
        "reviews": reviews,
    }
    return render(request, "reviews/index.html", context)


@login_required
def create(request):
    if request.method == "POST":
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect("reviews:detail", review.pk)
    else:
        form = ReviewForm()
    context = {
        "form": form,
    }
    return render(request, "reviews/create.html", context)


@login_required
def detail(request, pk):
    review = Review.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = review.comment_set.all()
    context = {
        "review": review,
        "comment_form": comment_form,
        "comments": comments,
    }
    return render(request, "reviews/detail.html", context)


@login_required
def update(request, pk):
    review = Review.objects.get(pk=pk)
    if request.user == review.user:
        if request.method == "POST":
            form = ReviewForm(request.POST, instance=review)
            if form.is_valid():
                form.save()
                return redirect("reviews:detail", review.pk)
        else:
            form = ReviewForm(instance=review)
        context = {
            "form": form,
            "review": review,
        }
        return render(request, "reviews/update.html", context)
    else:
        from django.http import HttpResponseForbidden

        return HttpResponseForbidden


@login_required
def delete(request, pk):
    review = Review.objects.get(pk=pk)
    if request.user == review.user:
        review.delete()
        return redirect("reviews:index")
    else:
        from django.http import HttpResponseForbidden

        return HttpResponseForbidden


def search(request):
    all_data = Review.objects.order_by("-pk")
    search = request.GET.get("search", "")
    if search:
        search_list = all_data.filter(
            Q(title__icontains=search) | Q(movie_name__icontains=search)
        )

        context = {
            "search_list": search_list,
        }
    else:
        context = {}

    return render(request, "reviews/search.html", context)


@login_required
def comments_create(request, pk):
    review = Review.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
        comments = []
        for a in review.comment_set.all():
            comments.append(
                [
                    a.content,
                    a.user.username,
                    a.create_at,
                    a.user.id,
                    request.user.id,
                    a.id,
                    a.review.id,
                ]
            )
        context = {"comments": comments}
        return JsonResponse(context)


@login_required
def comments_delete(request, review_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect("reviews:detail", review_pk)


@login_required
def likes(request, review_pk):
    review = Review.objects.get(pk=review_pk)

    if request.user in review.like_users.all():
        review.like_users.remove(request.user)
        is_Liked = False
    else:
        review.like_users.add(request.user)
        is_Liked = True
    context = {"isLiked": is_Liked, "likeCount": review.like_users.count()}
    return JsonResponse(context)

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}CREATE{% endblock title %}
{% block content %}

  <h1>CREATE</h1>
  <form action="" method="POST" enctype="multipart/form-data" class="create">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-outline-dark" value="작성">
  </form>

{% endblock content %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}detail{% endblock title %}
{% block content %}

  <h1>DETAIL</h1>
  <div class="container border py-3">
    <div class="d-flex justify-content-between">
      <h5 class="align-self-center mb-0">{{ review.pk }}번째 글</h5>
      <h3>{{ review.title }}</h3>
      <h5 class="align-self-center">
        <a href="{% url 'accounts:detail' review.user.pk %}">{{ review.user }}</a>
      </h5>
    </div>
    <hr>
    <div class="p-3 border">
      <h3 class="text-center">{{ review.movie_name }}</h3>
      {% if review.image %}
        <img src="{{ review.image.url}}" alt="">
      {% endif %}
    </div>
    <div class="container border my-2 pt-2">
      <p>내용 :
        {{ review.content }}</p>
    </div>
    <div class="container border my-2 pt-2">
      <p>평점 :
        {{ review.get_grade_display }}</p>
    </div>

    <!-- 좋아요 -->
    <div class='d-flex align-items-center'>
      {% if request.user.is_authenticated %}
        {% if request.user in review.like_users.all %}
          <i id='review-like' data-review-id='{{ review.pk }}' class="btn bi bi-heart-fill text-danger"></i>
        {% else %}
          <i id='review-like' data-review-id='{{ review.pk }}' class="btn bi bi-heart text-danger"></i>
        {% endif %}
      {% endif %}
      <span id='like-count'>{{ review.like_users.count }}개</span>
    </div>
    <div class="d-flex ms-2">
      <a class="btn btn-outline-dark me-2" href="{% url 'reviews:update' review.pk %}">수정하기</a>
      <form action="{% url 'reviews:delete' review.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-outline-dark me-2" value="삭제하기">
      </form>
      <a class="btn btn-outline-dark me-2" href="{% url 'reviews:index' %}">뒤로가기</a>
    </div>
    <hr><br>

    <!-- 댓글 작성 -->
    <form id='comment-form' data-review-id='{{ review.pk }}'>
      {% csrf_token %}
      {% bootstrap_form comment_form %}
      <input type="submit" class="btn btn-outline-dark" value="작성">
    </form>
    <hr><br>
    <!-- 댓글 목록-->
    <h5>댓글목록</h5>
    <br>
    <div id='comments'>
      {% for comment in comments %}
        <div class="d-flex align-items-center">
          <p class='ms-2 my-0' style='font-size:0.9rem;'>{{ comment.user }}</p>
          <p class='ms-2 text-secondary my-0' style='font-size:0.7rem;'>{{ comment.create_at }}</p>
        </div>
        <div class='d-flex align-items-center'>
          <p class='ms-2 my-0'>{{ comment.content }}</p>
          {% if request.user == comment.user %}
            <form class='mx-2' action="{% url 'reviews:comments_delete' review.pk comment.pk %}" method="POST">
              {% csrf_token %}
              <button class='btn p-0' type='submit'>
                <i class="bi bi-x-square text-danger"></i>
              </button>
            </form>
          {% endif %}
        </div>
        <hr>
      {% endfor %}
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const reviewLike = document.querySelector('#review-like')
    reviewLike.addEventListener('click', function (event) {
      axios({method: 'get', url: `/reviews/${event.target.dataset.reviewId}/likes/`}).then(response => {
        if (response.data.isLiked === true) {
          event
            .target
            .classList
            .remove('bi-heart')
          event
            .target
            .classList
            .add('bi-heart-fill')
        } else {
          event
            .target
            .classList
            .remove('bi-heart-fill')
          event
            .target
            .classList
            .add('bi-heart')
        }
        const likeCount = document.querySelector('#like-count')
        likeCount.innerText = `${response.data.likeCount}개`
      })
    })
  </script>
  <script>
    const commentForm = document.querySelector('#comment-form')
    const csrftoken = document
      .querySelector('[name=csrfmiddlewaretoken]')
      .value
      commentForm
      .addEventListener('submit', function (event) {
        event.preventDefault();
        axios({
          method: 'post',
          url: `/reviews/${event.target.dataset.reviewId}/comments/`,
          headers: {
            'X-CSRFToken': csrftoken
          },
          data: new FormData(commentForm)
        }).then(response => {
          const comments = document.querySelector('#comments')
          comments.replaceChildren()
          for (comment of response.data.comments) {
            const hr = document.createElement('hr')

            const div1 = document.createElement('div')
            div1
              .classList
              .add('d-flex', 'align-items-center')

            const div2 = document.createElement('div')
            div2
              .classList
              .add('d-flex', 'align-items-center')

            const p1 = document.createElement('p')
            p1
              .classList
              .add('ms-2', 'my-0')
            p1.setAttribute('style', 'font-size:0.9rem;')
            p1.innerText = `${comment[1]}`

            const p2 = document.createElement('p')
            p2
              .classList
              .add('ms-2', 'text-secondary', 'my-0')
            p2.setAttribute('style', 'font-size:0.7rem;')
            if (parseInt(new Date(comment[2]).getHours()) >= 12) {
              p2.innerText = `${new Date(comment[2]).getFullYear()}년 ${new Date(comment[2]).getMonth() + 1}월 ${new Date(comment[2]).getDate()}일 ${parseInt(new Date(comment[2]).getHours()) - 12}:${new Date(comment[2]).getMinutes()} 오후`
            } else {
              p2.innerText = `${new Date(comment[2]).getFullYear()}년 ${new Date(comment[2]).getMonth() + 1}월 ${new Date(comment[2]).getDate()}일 ${new Date(comment[2]).getHours()}:${new Date(comment[2]).getMinutes()} 오전`
            }

            const p3 = document.createElement('p')
            p3
              .classList
              .add('ms-2', 'my-0')
            p3.innerText = `${comment[0]}`

            div1.append(p1, p2)
            div2.append(p3)
            if (comment[3] === comment[4]) {
              const form = document.createElement('form')
              form
                .classList
                .add('mx-2')
              form.setAttribute('action', `/reviews/${comment[6]}/comments/${comment[5]}/delete/`)
              const button = document.createElement('button')
              button
                .classList
                .add('btn', 'p-0')
              const i = document.createElement('i')
              i
                .classList
                .add('bi', 'bi-x-square', 'text-danger')
              button.append(i)
              form.append(button)
              div2.append(form)
            }
            comments.append(div1, div2, hr)
          }
          commentForm.reset()
        })
      })
  </script>
{% endblock content %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>게시판</h1>

  <form class="search d-flex mb-5" role="search" action="{% url 'reviews:search' %}">
    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
    <button class="btn btn-outline-dark" type="submit">Search</button>
  </form>

  <table class="table text-center border-dark">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">글 제목</th>
        <th scope="col">영화 제목</th>
        <th scope="col">평점</th>
        <th scope="col">비고</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      {% for review in reviews %}
        <tr class="tbtr">
          <th scope="row">{{ review.pk }}</th>
          <td>{{ review.title }}</td>
          <td>{{ review.movie_name }}</td>
          <td>{{ review.get_grade_display  }}</td>
          <td>
            <a class="detail-link" href="{% url 'reviews:detail' review.pk %}">자세히</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

reviews/templates/reviews/search.html
{% extends 'base.html' %}

{% block content %}
  <h1>검색결과</h1>

  <form class="search d-flex mb-5" role="search" action="{% url 'reviews:search' %}">
    <input class="form-control me-2" type="search" placeholder="Search" name="search" aria-label="Search">
    <button class="btn btn-outline-dark" type="submit">Search</button>
  </form>

  <table class="table text-center border-dark">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">글 제목</th>
        <th scope="col">영화 제목</th>
        <th scope="col">평점</th>
        <th scope="col">비고</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      {% for review in search_list %}
        <tr>
          <th scope="row">{{ review.pk }}</th>
          <td>{{ review.title }}</td>
          <td>{{ review.movie_name }}</td>
          <td>{{ review.get_grade_display  }}</td>
          <td>
            <a href="{% url 'reviews:detail' review.pk %}">자세히</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <a class="btn btn-outline-dark" href="{% url 'reviews:index' %}">뒤로가기</a>
{% endblock content %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}UPDATE{% endblock title %}

{% block content %}
  <h1>UPDATE</h1>
  <form action="{% url 'reviews:update' review.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-outline-dark" type="submit" value="수정">
    <a href="{% url 'reviews:detail' review.pk %}" class="btn btn-outline-dark">뒤로가기</a>
  </form>

{% endblock content %}