accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:pk>/', views.detail, name='detail'),
    path('update/', views.update, name='update'),
    path('password/', views.password_update, name='password_update'),
    path('delete/', views.delete, name='delete'),
    path('<int:pk>/follow/', views.follow, name='follow'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("reviews/", include("reviews.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("search/", views.search, name="search"),
    path("<int:pk>/comments/", views.comments_create, name="comments_create"),
    path(
        "<int:review_pk>/comments/<int:comment_pk>/delete/",
        views.comments_delete,
        name="comments_delete",
    ),
    path("<int:review_pk>/likes/", views.likes, name="likes"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
# Create your models here.

class User(AbstractUser):
    followings = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followers")

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ["username", "last_name", "first_name", "email"]


class CustomUserChangeForm(UserChangeForm):
    password = None
    class Meta:
        model = get_user_model()
        fields = ["last_name", "first_name", "email"]

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.contrib.auth import (
    login as auth_login,
    logout as auth_logout,
    get_user_model,
    update_session_auth_hash,
)
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse


# Create your views here.
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("reviews:index")
    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "reviews:index")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect("accounts:login")


@login_required
def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        "user": user,
        'reviews': user.review_set.all(),
        'comments': user.comment_set.all(),
    }
    return render(request, "accounts/detail.html", context)


@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:detail", request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)


@login_required
def password_update(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("accounts:detail", request.user.pk)
    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/password_update.html", context)


@login_required
def delete(request):
    if request.method == "POST":
        request.user.delete()
        auth_logout(request)
        return redirect("accounts:login")


@login_required
def follow(request, pk):
    user = get_user_model().objects.get(pk=pk)
    if request.user != user:
        if request.user.followings.filter(id=user.pk).exists():
            request.user.followings.remove(user)
            is_followed = False
        else:
            request.user.followings.add(user)
            is_followed = True
        context = {
            "is_followed": is_followed,
            "followers_count": user.followers.count(),
            "followings_count": user.followings.count(),
        }
        return JsonResponse(context)

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <div class="card h-auto">
    <div class="card-header">
      <h3>
        {{ user.username }}님의 페이지</h3>
    </div>
    <div class="card-body">
      <h5 class="card-title">이름 :
        {{ user.last_name }}{{ user.first_name }}</h5>
      <p class="card-text">이메일 :
        {{ user.email }}</p>
      <div class="my-3">
        follower :
        <span id="followers-count">{{ user.followers.all|length }}</span>
        | following :
        <span id="followings-count">{{ user.followings.all|length }}</span>
        <div class="row">
          <div class="col-6 h-100">
            <div class="card w-auto h-auto mt-3">
              <div class="card-body">
                <h5 class="card-title mb-4">작성한 글</h5>
                {% for review in reviews %}
                  <div class="d-flex justify-content-between">
                    <a class="ellipsis card-text" href="{% url 'reviews:detail' review.pk %}">{{ review.title }}</a>
                    <p class='mx-2 my-0'>{{ review.created_at }}</p>
                  </div>
                  <hr>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="col-6 h-100">
            <div class="card w-auto h-auto mt-3">
              <div class="card-body">
                <h5 class="card-title mb-4">작성한 댓글</h5>
                {% for comment in comments %}
                  <div class="d-flex justify-content-between">
                    <a class="ellipsis card-text" href="{% url 'reviews:detail' comment.review.pk %}">{{ comment.content }}</a>
                    <p class='mx-2 my-0'>{{ comment.create_at }}</p>
                  </div>
                  <hr>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>

      {% if request.user.is_authenticated %}
        {% if request.user != user %}
          <form id="follow-form" data-user-id="{{ user.pk }}" class="text-center">
            {% csrf_token %}
            {% if request.user in user.followers.all %}
              <input class="btn btn-outline-dark" type="submit" value="Unfollow">
            {% else %}
              <input class="btn btn-outline-dark" type="submit" value="follow">
            {% endif %}
          </form>
        {% else %}
          <div class="d-flex justify-content-center">
            <a class='btn btn-outline-dark' href="{% url 'accounts:update' %}">수정</a>
            <button type="button" class="btn btn-outline-dark mx-2" data-bs-toggle="modal" data-bs-target="#exampleModal">
              탈퇴
            </button>
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title m-0 fs-5" id="exampleModalLabel">정말 탈퇴하시겠습니까?</h1>
                  </div>
                  <div class="modal-body text-start">
                    탈퇴된 계정은 복구할 수 없습니다.
                  </div>
                  <div class="modal-footer">
                    <form action="{% url 'accounts:delete' %}" method="POST">
                      {% csrf_token %}
                      <input class='btn btn-outline-danger' type="submit" value='탈퇴'>
                    </form>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">아니오</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endif %}
      {% endif %}
    </div>
    <div class="card-footer">
      <p class="my-auto">마지막 활동 :
        {{ user.last_login }}</p>
    </div>
  </div>

  <!-- script -->
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const form = document.querySelector('#follow-form')
    if (form) {
      const csrftoken = document
        .querySelector('[name=csrfmiddlewaretoken]')
        .value

        form
        .addEventListener('submit', function (event) {
          event.preventDefault()

          const userId = event
            .target
            .dataset
            .userId
            axios({
              method: 'post',
              url: `/accounts/${userId}/follow/`,
              headers: {
                'X-CSRFToken': csrftoken
              }
            })
            .then((response) => {
              const isFollowed = response.data.is_followed
              const followBtn = document.querySelector('#follow-form > input[type=submit]')
              if (isFollowed === true) {
                followBtn.value = 'Unfollow'
              } else {
                followBtn.value = 'follow'
              }

              const followersCountTag = document.querySelector('#followers-count')
              const followingsCountTag = document.querySelector('#followings-count')
              const followersCount = response.data.followers_count
              const followingsCount = response.data.followings_count
              followersCountTag.innerText = followersCount
              followingsCountTag.innerText = followingsCount
            })
            .catch((error) => {
              console.log(error.response)
            })
          })
    }
  </script>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>LOGIN</h1>
  <form action="" method="POST" class="login">
    {% csrf_token %}
    {% bootstrap_form form%}
    <input class="btn btn-outline-dark" type="submit" value="로그인">
  </form>
{% endblock content %}

accounts/templates/accounts/password_update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>PASSWORD_UPDATE</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form%}
    <input type="submit">
  </form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>SIGNUP</h1>
  <form action="" method="POST" class="signup">
    {% csrf_token %}
    {% bootstrap_form form%}
    <input class="btn btn-outline-dark" type="submit" value="회원가입">
  </form>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>UPDATE</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <a class="btn btn-outline-dark" href="{% url 'accounts:password_update' %}">비밀번호 변경</a>
    <input class="btn btn-outline-dark" type="submit">
  </form>
{% endblock content %}